"use strict";

import { batchAssert } from "../../test/assert.mjs";
import Batch from "../Batch/Batch.mjs";
import Cell from "../Cell/Cell.mjs";
import SudokuBoard from "../SudokuBoard.mjs";

const puzzle2d = [
  [1, 0, 0, 0, 0, 7, 0, 0, 3],
  [9, 0, 6, 0, 0, 8, 2, 0, 4],
  [0, 3, 0, 5, 2, 0, 0, 9, 0],
  [3, 9, 0, 0, 0, 1, 5, 0, 0],
  [0, 0, 5, 0, 0, 0, 9, 0, 0],
  [0, 0, 1, 2, 0, 0, 0, 4, 7],
  [0, 2, 0, 0, 6, 5, 0, 1, 0],
  [5, 0, 8, 1, 0, 0, 7, 0, 2],
  [6, 0, 0, 7, 0, 0, 0, 0, 5],
];
const puzzle1d = puzzle2d.flat();
const puzleStr = puzzle1d.join("");
const unsolvable2d = [
  [0, 1, 2, 3, 4, 5, 6, 7, 8],
  [9, 0, 0, 0, 0, 0, 0, 0, 0],
  [8, 0, 0, 0, 0, 0, 0, 0, 0],
  [7, 0, 0, 0, 0, 0, 0, 0, 0],
  [6, 0, 0, 0, 0, 0, 0, 0, 0],
  [5, 0, 0, 0, 0, 0, 0, 0, 0],
  [4, 0, 0, 0, 0, 0, 0, 0, 0],
  [3, 0, 0, 0, 0, 0, 0, 0, 0],
  [2, 0, 0, 0, 0, 0, 0, 0, 0],
];
const unsolvable1d = unsolvable2d.flat();
const unsolvableStr = unsolvable1d.join("");
const wrong2d = [
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
  [1, 2, 3, 4, 5, 6, 7, 8, 9],
];
const wrong1d = wrong2d.flat();
const wrongStr = wrong1d.join("");

const board = new SudokuBoard(3, 3);

const cases = [
  {
    caseDesc: "Getting the board properties.",
    first: null,
    check: () => board.info,
    excepted: [
      {
        id: 0,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 1,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 2,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 3,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 4,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 5,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 6,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 7,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 8,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 9,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 10,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 11,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 12,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 13,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 14,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 15,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 1,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 16,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 1,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 17,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 1,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 18,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 19,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 20,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 21,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 22,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 23,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 24,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 25,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 26,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 27,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 28,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 29,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 30,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 31,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 32,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 33,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 34,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 35,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 36,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 37,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 38,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 39,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 40,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 41,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 42,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 43,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 44,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 45,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 46,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 47,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 48,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 49,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 50,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 51,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 52,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 53,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 54,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 55,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 56,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 57,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 58,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 59,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 60,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 6,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 61,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 6,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 62,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 6,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 63,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 64,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 65,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 66,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 67,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 68,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 69,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 7,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 70,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 7,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 71,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 7,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 72,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 73,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 74,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 75,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 76,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 77,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 78,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 8,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 79,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 8,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 80,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 8,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
  {
    caseDesc: "Getting the first row.",
    first: null,
    check: () => board.getRow(0).info,
    excepted: [
      {
        id: 0,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 1,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 2,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 3,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 4,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 5,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 6,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 7,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 8,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
  {
    caseDesc: "Getting the third row.",
    first: null,
    check: () => board.getRow(2).info,
    excepted: [
      {
        id: 18,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 19,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 20,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 21,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 22,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 23,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 24,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 25,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 26,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
  {
    caseDesc: "Getting all rows.",
    first: null,
    check: () => board.getAllRows().map((row) => row.info),
    excepted: [
      [
        {
          id: 0,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 0,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 1,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 0,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 2,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 0,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 3,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 0,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 4,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 0,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 5,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 0,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 6,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 0,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 7,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 0,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 8,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 0,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 9,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 1,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 10,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 1,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 11,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 1,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 12,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 1,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 13,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 1,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 14,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 1,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 15,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 1,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 16,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 1,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 17,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 1,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 18,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 2,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 19,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 2,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 20,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 2,
          bx: 0,
          by: 0,
          boxId: 0,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 21,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 2,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 22,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 2,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 23,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 2,
          bx: 1,
          by: 0,
          boxId: 1,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 24,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 2,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 25,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 2,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 26,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 2,
          bx: 2,
          by: 0,
          boxId: 2,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 27,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 3,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 28,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 3,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 29,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 3,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 30,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 3,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 31,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 3,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 32,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 3,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 33,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 3,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 34,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 3,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 35,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 3,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 36,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 4,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 37,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 4,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 38,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 4,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 39,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 4,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 40,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 4,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 41,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 4,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 42,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 4,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 43,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 4,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 44,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 4,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 45,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 5,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 46,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 5,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 47,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 5,
          bx: 0,
          by: 1,
          boxId: 3,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 48,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 5,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 49,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 5,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 50,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 5,
          bx: 1,
          by: 1,
          boxId: 4,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 51,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 5,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 52,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 5,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 53,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 5,
          bx: 2,
          by: 1,
          boxId: 5,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 54,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 6,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 55,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 6,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 56,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 6,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 57,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 6,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 58,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 6,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 59,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 6,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 60,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 6,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 61,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 6,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 62,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 6,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 63,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 7,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 64,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 7,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 65,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 7,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 66,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 7,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 67,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 7,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 68,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 7,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 69,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 7,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 70,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 7,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 71,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 7,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
      [
        {
          id: 72,
          given: false,
          issued: false,
          value: 0,
          x: 0,
          y: 8,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 73,
          given: false,
          issued: false,
          value: 0,
          x: 1,
          y: 8,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 74,
          given: false,
          issued: false,
          value: 0,
          x: 2,
          y: 8,
          bx: 0,
          by: 2,
          boxId: 6,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 75,
          given: false,
          issued: false,
          value: 0,
          x: 3,
          y: 8,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 76,
          given: false,
          issued: false,
          value: 0,
          x: 4,
          y: 8,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 77,
          given: false,
          issued: false,
          value: 0,
          x: 5,
          y: 8,
          bx: 1,
          by: 2,
          boxId: 7,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 78,
          given: false,
          issued: false,
          value: 0,
          x: 6,
          y: 8,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 79,
          given: false,
          issued: false,
          value: 0,
          x: 7,
          y: 8,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
        {
          id: 80,
          given: false,
          issued: false,
          value: 0,
          x: 8,
          y: 8,
          bx: 2,
          by: 2,
          boxId: 8,
          accepted: { unfilled: 0, min: 1, max: 9 },
        },
      ],
    ],
  },
  {
    caseDesc: "Getting first column.",
    first: null,
    check: () => board.getCol(0).info,
    excepted: [
      {
        id: 0,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 9,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 18,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 27,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 36,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 45,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 54,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 63,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 72,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
  {
    caseDesc: "Getting fourth column.",
    first: null,
    check: () => board.getCol(3).info,
    excepted: [
      {
        id: 3,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 12,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 21,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 30,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 39,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 48,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 57,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 66,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 75,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
  {
    caseDesc: "Getting first box.",
    first: null,
    check: () => board.getBox(0).info,
    excepted: [
      {
        id: 0,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 1,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 2,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 9,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 10,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 11,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 18,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 19,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 20,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
  {
    caseDesc: "Getting sixt box.",
    first: null,
    check: () => board.getBox(5).info,
    excepted: [
      {
        id: 33,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 34,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 35,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 42,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 43,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 44,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 51,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 52,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 53,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },

  {
    caseDesc: "Setting the board to puzzle1 as 2D array.",
    first: () => board.setBoard(puzzle2d),
    check: () => board.info,
    excepted: [
      {
        id: 0,
        given: false,
        issued: false,
        value: 1,
        x: 0,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 1,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 2,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 0,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 3,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 4,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 5,
        given: false,
        issued: false,
        value: 7,
        x: 5,
        y: 0,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 6,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 7,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 8,
        given: false,
        issued: false,
        value: 3,
        x: 8,
        y: 0,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 9,
        given: false,
        issued: false,
        value: 9,
        x: 0,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 10,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 11,
        given: false,
        issued: false,
        value: 6,
        x: 2,
        y: 1,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 12,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 13,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 14,
        given: false,
        issued: false,
        value: 8,
        x: 5,
        y: 1,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 15,
        given: false,
        issued: false,
        value: 2,
        x: 6,
        y: 1,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 16,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 1,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 17,
        given: false,
        issued: false,
        value: 4,
        x: 8,
        y: 1,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 18,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 19,
        given: false,
        issued: false,
        value: 3,
        x: 1,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 20,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 2,
        bx: 0,
        by: 0,
        boxId: 0,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 21,
        given: false,
        issued: false,
        value: 5,
        x: 3,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 22,
        given: false,
        issued: false,
        value: 2,
        x: 4,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 23,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 2,
        bx: 1,
        by: 0,
        boxId: 1,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 24,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 25,
        given: false,
        issued: false,
        value: 9,
        x: 7,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 26,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 2,
        bx: 2,
        by: 0,
        boxId: 2,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 27,
        given: false,
        issued: false,
        value: 3,
        x: 0,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 28,
        given: false,
        issued: false,
        value: 9,
        x: 1,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 29,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 3,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 30,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 31,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 32,
        given: false,
        issued: false,
        value: 1,
        x: 5,
        y: 3,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 33,
        given: false,
        issued: false,
        value: 5,
        x: 6,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 34,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 35,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 3,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 36,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 37,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 38,
        given: false,
        issued: false,
        value: 5,
        x: 2,
        y: 4,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 39,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 40,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 41,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 4,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 42,
        given: false,
        issued: false,
        value: 9,
        x: 6,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 43,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 44,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 4,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 45,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 46,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 47,
        given: false,
        issued: false,
        value: 1,
        x: 2,
        y: 5,
        bx: 0,
        by: 1,
        boxId: 3,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 48,
        given: false,
        issued: false,
        value: 2,
        x: 3,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 49,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 50,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 5,
        bx: 1,
        by: 1,
        boxId: 4,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 51,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 52,
        given: false,
        issued: false,
        value: 4,
        x: 7,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 53,
        given: false,
        issued: false,
        value: 7,
        x: 8,
        y: 5,
        bx: 2,
        by: 1,
        boxId: 5,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 54,
        given: false,
        issued: false,
        value: 0,
        x: 0,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 55,
        given: false,
        issued: false,
        value: 2,
        x: 1,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 56,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 6,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 57,
        given: false,
        issued: false,
        value: 0,
        x: 3,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 58,
        given: false,
        issued: false,
        value: 6,
        x: 4,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 59,
        given: false,
        issued: false,
        value: 5,
        x: 5,
        y: 6,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 60,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 6,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 61,
        given: false,
        issued: false,
        value: 1,
        x: 7,
        y: 6,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 62,
        given: false,
        issued: false,
        value: 0,
        x: 8,
        y: 6,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 63,
        given: false,
        issued: false,
        value: 5,
        x: 0,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 64,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 65,
        given: false,
        issued: false,
        value: 8,
        x: 2,
        y: 7,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 66,
        given: false,
        issued: false,
        value: 1,
        x: 3,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 67,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 68,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 7,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 69,
        given: false,
        issued: false,
        value: 7,
        x: 6,
        y: 7,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 70,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 7,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 71,
        given: false,
        issued: false,
        value: 2,
        x: 8,
        y: 7,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 72,
        given: false,
        issued: false,
        value: 6,
        x: 0,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 73,
        given: false,
        issued: false,
        value: 0,
        x: 1,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 74,
        given: false,
        issued: false,
        value: 0,
        x: 2,
        y: 8,
        bx: 0,
        by: 2,
        boxId: 6,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 75,
        given: false,
        issued: false,
        value: 7,
        x: 3,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 76,
        given: false,
        issued: false,
        value: 0,
        x: 4,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 77,
        given: false,
        issued: false,
        value: 0,
        x: 5,
        y: 8,
        bx: 1,
        by: 2,
        boxId: 7,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 78,
        given: false,
        issued: false,
        value: 0,
        x: 6,
        y: 8,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 79,
        given: false,
        issued: false,
        value: 0,
        x: 7,
        y: 8,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
      {
        id: 80,
        given: false,
        issued: false,
        value: 5,
        x: 8,
        y: 8,
        bx: 2,
        by: 2,
        boxId: 8,
        accepted: { unfilled: 0, min: 1, max: 9 },
      },
    ],
  },
];

batchAssert(cases, {
  showFailed: true,
  showSuccessed: false,
  length: Infinity,
});
